In [21]:
import numpy as np
import torchvision.models.segmentation
import torch
import torchvision.transforms as tf
from PIL import Image
import scipy.io

Learning_Rate=1e-5
width=891
height=645
batchSize=1

In [22]:
image = Image.open('trainingdataimages/gentrain_001.png')
data = np.asarray(image)
print(image.format)
print(image.size)
print(image.mode)
# show the image
# image.show()
print(type(data))
print(data.shape)
print(data)

PNG
(690, 526)
RGB
<class 'numpy.ndarray'>
(526, 690, 3)
[[[ 99 204 111]
  [ 99 204 111]
  [ 99 204 111]
  ...
  [171 198  56]
  [171 198  56]
  [171 198  56]]

 [[ 99 204 111]
  [ 99 204 111]
  [ 99 204 111]
  ...
  [171 198  56]
  [171 198  56]
  [171 198  56]]

 [[ 99 204 111]
  [ 99 204 111]
  [ 99 204 111]
  ...
  [171 198  56]
  [171 198  56]
  [171 198  56]]

 ...

 [[ 39 150 235]
  [ 39 150 235]
  [ 39 150 235]
  ...
  [ 24 191 181]
  [ 24 191 181]
  [ 24 191 181]]

 [[ 39 150 235]
  [ 39 150 235]
  [ 39 150 235]
  ...
  [ 24 191 181]
  [ 24 191 181]
  [ 24 191 181]]

 [[ 39 150 235]
  [ 39 150 235]
  [ 39 150 235]
  ...
  [ 24 191 181]
  [ 24 191 181]
  [ 24 191 181]]]


In [23]:
def ReadImage():
    fname = 'trainingdataimages/gentrain_001.png'
    file = fname.split('/')[1]
    matfile = 'trainingdatavalues/' + file[:len(file) - 4] + '.mat'
    mat = scipy.io.loadmat(matfile)
    image = Image.open('trainingdataimages/gentrain_001.png')
    data = np.asarray(image)
    transformImg=tf.Compose([tf.ToPILImage(),tf.Resize((height,width)),tf.ToTensor()])

    data = transformImg(data)
    return data, mat['th0'][0]

ReadImage()

(tensor([[[0.3882, 0.3882, 0.3882,  ..., 0.6706, 0.6706, 0.6706],
          [0.3882, 0.3882, 0.3882,  ..., 0.6706, 0.6706, 0.6706],
          [0.3882, 0.3882, 0.3882,  ..., 0.6706, 0.6706, 0.6706],
          ...,
          [0.1529, 0.1529, 0.1529,  ..., 0.0941, 0.0941, 0.0941],
          [0.1529, 0.1529, 0.1529,  ..., 0.0941, 0.0941, 0.0941],
          [0.1529, 0.1529, 0.1529,  ..., 0.0941, 0.0941, 0.0941]],
 
         [[0.8000, 0.8000, 0.8000,  ..., 0.7765, 0.7765, 0.7765],
          [0.8000, 0.8000, 0.8000,  ..., 0.7765, 0.7765, 0.7765],
          [0.8000, 0.8000, 0.8000,  ..., 0.7765, 0.7765, 0.7765],
          ...,
          [0.5882, 0.5882, 0.5882,  ..., 0.7490, 0.7490, 0.7490],
          [0.5882, 0.5882, 0.5882,  ..., 0.7490, 0.7490, 0.7490],
          [0.5882, 0.5882, 0.5882,  ..., 0.7490, 0.7490, 0.7490]],
 
         [[0.4353, 0.4353, 0.4353,  ..., 0.2196, 0.2196, 0.2196],
          [0.4353, 0.4353, 0.4353,  ..., 0.2196, 0.2196, 0.2196],
          [0.4353, 0.4353, 0.4353,  ...,

In [24]:
def LoadBatch(): # Load batch of images
    images = torch.zeros([batchSize,3,height,width])
    theta0 = torch.zeros([batchSize,3])
    for i in range(batchSize):
        x,y = ReadImage()
        images[i],theta0[i]=x, torch.from_numpy(y)
    return images,theta0

LoadBatch()

(tensor([[[[0.3882, 0.3882, 0.3882,  ..., 0.6706, 0.6706, 0.6706],
           [0.3882, 0.3882, 0.3882,  ..., 0.6706, 0.6706, 0.6706],
           [0.3882, 0.3882, 0.3882,  ..., 0.6706, 0.6706, 0.6706],
           ...,
           [0.1529, 0.1529, 0.1529,  ..., 0.0941, 0.0941, 0.0941],
           [0.1529, 0.1529, 0.1529,  ..., 0.0941, 0.0941, 0.0941],
           [0.1529, 0.1529, 0.1529,  ..., 0.0941, 0.0941, 0.0941]],
 
          [[0.8000, 0.8000, 0.8000,  ..., 0.7765, 0.7765, 0.7765],
           [0.8000, 0.8000, 0.8000,  ..., 0.7765, 0.7765, 0.7765],
           [0.8000, 0.8000, 0.8000,  ..., 0.7765, 0.7765, 0.7765],
           ...,
           [0.5882, 0.5882, 0.5882,  ..., 0.7490, 0.7490, 0.7490],
           [0.5882, 0.5882, 0.5882,  ..., 0.7490, 0.7490, 0.7490],
           [0.5882, 0.5882, 0.5882,  ..., 0.7490, 0.7490, 0.7490]],
 
          [[0.4353, 0.4353, 0.4353,  ..., 0.2196, 0.2196, 0.2196],
           [0.4353, 0.4353, 0.4353,  ..., 0.2196, 0.2196, 0.2196],
           [0.4353, 0.43